import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';
import './globals.css';

import { ClerkProvider } from '@clerk/nextjs';

const comfortaa = Comfortaa({ weight: ['400', '500'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={comfortaa.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
